# Generated by Django 5.1.2 on 2024-10-15 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_testimonial_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='instructors/')),
                ('bio', models.TextField(blank=True, null=True)),
                ('rating', models.FloatField(default=0.0)),
                ('students', models.IntegerField(default=0)),
                ('courses_count', models.IntegerField(default=0)),
                ('reviews', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='courses/')),
                ('description', models.TextField()),
                ('rating', models.FloatField(default=0.0)),
                ('rating_count', models.IntegerField()),
                ('duration', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.category')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.instructor')),
                ('languages', models.ManyToManyField(related_name='courses', to='web.language')),
            ],
        ),
    ]
