# Generated by Django 5.1.2 on 2024-10-15 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_rename_name_language_languages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categories',
        ),
        migrations.RenameModel(
            old_name='Course',
            new_name='Courses',
        ),
        migrations.RenameModel(
            old_name='Instructor',
            new_name='Instructors',
        ),
        migrations.RenameModel(
            old_name='Language',
            new_name='Languages',
        ),
    ]
