# Generated by Django 5.1.2 on 2024-10-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_rename_category_categories_rename_course_courses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='icon',
            field=models.FileField(default='abcd', upload_to='categories/'),
            preserve_default=False,
        ),
    ]
