# Generated by Django 5.1.2 on 2024-10-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_categories_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructors',
            name='image',
            field=models.ImageField(upload_to='instructors/'),
        ),
    ]
