# Generated by Django 5.1.2 on 2024-10-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_instructors_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='discount_percent',
            field=models.IntegerField(),
        ),
    ]
