# Generated by Django 5.1.2 on 2024-10-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_courses_discount_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='discount_percent',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=2),
        ),
    ]
