# Generated by Django 5.1.2 on 2024-10-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_alter_courses_discount_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
