# Generated by Django 5.1.2 on 2024-10-16 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_courses_certification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('lessons', models.PositiveIntegerField()),
                ('duration', models.CharField(max_length=50)),
                ('top_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus', to='web.courses')),
            ],
        ),
    ]
