# Generated by Django 5.1.2 on 2024-10-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_syllabus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructors',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='instructors/'),
        ),
    ]
