# Generated by Django 5.1.2 on 2024-10-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_alter_courses_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='category',
        ),
        migrations.AddField(
            model_name='courses',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='courses', to='web.categories'),
        ),
        migrations.DeleteModel(
            name='Syllabus',
        ),
    ]
