# Generated by Django 5.1.2 on 2024-10-21 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_syllabus'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='course',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='syllabi', to='web.courses'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='duration',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='lessons',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
